# Введение {.unnumbered}

Эта книга посвящена географии юридических услуг в России. Одновременно я рассчитываю превратить её в кандидатскую диссертацию с минимальными отличиями от книги, поэтому стиль изложения научный, а некоторые вещи наподобие названий глав и подписей к таблицам и изображениям весьма формализованы. Думаю, что писать книгу, которая одновременно диссертация, куда интереснее, чем писать диссертацию. Кроме того, вы тоже можете её прочитать и написать мне отзыв — например, заведя Issue на GitHub, где весь «код» этой книги, собственно, и хранится. 

Технически эта книга написана с помощью [Quarto](https://quarto.org/docs/books) — весьма многофункциональной и гибкой штуки, которая позволяет совместить текст и код (который нужен, например, для графиков), по минимуму беспокоиться о тонкостях оформления и подготовить книгу сразу в нескольких форматах (например, сайт, PDF и Word). Можете тоже посмотреть, что это такое: вдруг пригодится :)

## Объект, предмет, цели, задачи

В итоговом варианте диссертации во введении должны быть чётко обозначены объект, предмет, цели и задачи исследования — так положено и так следует из методологии науки. Тем не менее, здесь пока не итоговый вариант — во всяком случае, если говорить о введении — поэтому можно позволить себе некоторые вольности и рассуждения, которые, вероятно, потом позволят сформулировать строгий «формализованный» вариант введения.

Традиционно считается, что исследователь определяет объект и предмет своей работы, равно как формулирует цели и задачи *до* начала собственно исследования. В случае с географией он также уточняет изучаемый район: весь мир, отдельная страна (например, Россия), физико-географическая область (например, Бразильское плоскогорье), экономический район (например, Центрально-Черноземный), населённый пункт (скажем, Москва). К сожалению, из всего этого мне в данный момент подходит только выбор района исследования: могу заявить, что это Россия в целом (и то, увы, не уверен о конкретных границах, учитывая наличие, так сказать, территорий со спорным международным статусом, «официальный» статус которых, тем не менее, настолько однозначен, что любые отступления от него, пусть даже в научной работе, грозят уголовным преследованием). С остальным же возникают трудности двух видов. С одной стороны, несмотря на то что предварительное определение объекта-предмета-целей-задач считается «золотым стандартном» хорошего исследования, я пока не встречал ни одного учёного, который *действительно* знал бы всё это *до* начала исследования. Конечно, исследователь уже знает *что-то*, и в некоторых ситуациях, опираясь на предыдущие исследования, может довольно чётко сформулировать всё указанное выше, однако чем более обширным и пространным является предметное поле, тем больше шанс, что в процессе он обнаружит нечто, что заставит его уточнить первоначальные формулировки. Как писал, если не ошибаюсь, К. Поппер, наука представляет собой в основном искусство задавать вопросы, и каждый новый ответ ведёт лишь к новым вопросам — значит, и объект-предмет-цели-задачи будут корректироваться по мере исследования, особенно если оно преимущественно поисковое. С другой стороны, моё исследование является, как я скажу чуть ниже, основанным на данных, и мой опыт анализа данных показывает, что ограничиваться постановкой заранее известных вопросов к данным — это значит вдвое сузить круг потенциальных выводов. Нужно не только искать в данных ответы на готовые вопросы, но и смотреть, какие готовые ответы находятся в данных с тем, чтобы сформулировать вопросы для этих ответов. Таким образом, несмотря на то что в конце концов в диссертации неизбежно будут определены объект-предмет-цели-задачи, причём определены так, как будто они известны заранее, на самом деле исследование велось по спирали: от первоначальных вопросов к первоначальным ответам, от них к новым вопросам и новым ответам, и так до тех пор, пока глубина получившегося «карьера» не стала достаточной для того, чтобы можно было решить, что это «месторождение» отработано, и пора фиксировать результат.

Несмотря на это, мне всё же необходимо сразу описать своё видение объекта, предмета, целей и задач — хотя бы обобщённое и поверхностное — потому что иначе кажется, будто я не знаю, что делаю и чего хочу, а это не так. Объектом является рынок юридических услуг в России, а предметом — его географические (пространственные) характеристики и закономерности. Это неизбежно спорные формулировки, но я думаю, что они имеют право на существование. Погружаться в задачи я не буду, так как они станут очевидны из всего дальнейшего текста, а вот на целях остановлюсь чуть подробнее. Я бы выделил две основные цели — или, можно даже сказать, «исследовательские мотивации».

Первая цель — это описать географию юридических услуг в России и выявить её закономерности. Считается, что описание — это «плохая» цель: либо слишком низкоуровневая и интеллектуально примитивная, либо вовсе ненаучная и играющая лишь методическую (вспомогательную) роль — проще говоря, «настоящий учёный» такими вещами не занимается. Отчасти соглашусь, особенно если следовать трактовке науки как деятельности по обнаружению универсальных законов природы — но замечу также, что география, согласно одной из двух философских трактовок, — это наука идеографическая, то есть описательная по своей сути. Кроме того, описание хоть и выглядит чем-то «простым», представляет собой тем не менее важное направление академической деятельности: поиск новых видов живых организмов, определение характеристик далёких планетных систем или составление глобальных карт доступности медицинских услуг — это по сути именно описание, только научное, то есть отличающееся некоторыми характеристиками от обыденного, художественного, мифологического или религиозного. Соответственно, я не вижу ничего зазорного в том, чтобы сделать географическое описание юридических услуг в России — учитывая, что данный вопрос привлекал мало внимания других исследователей: мне известно всего лишь две работы академических специалистов, затрагивающих пространственные аспекты рынка юридических услуг в России. В то же время отмечу, что я не планирую забывать о другом философском подходе к географии как к номотетической, то есть «нормальной», изучающей закономерности  науке, и постараюсь по мере воможностей — с учётом всех прочих характеристик исследования — найти и какие-то закономерности. Применительно к географии речь идёт в первую очередь о факторах размещения, а во-вторых, о проверке ряда «стандартных» общественно-географических закономерностей, таких как «центр-периферия», «ранг-размер» и тому подобных.

Вторая цель, для меня не менее важная, чем первая — а в плане «добавленной ценности» для науки, может быть, и более важная — это разработать и валидировать на конкретном примере методику работы с данными. «Конкретным примером» будет само данное исследование, то есть оно сочетает в себе два аспекта: собственно исследовательский и методологический. Я имею в виду, что исследование будет, как я уже говорил выше, основанным на данных — или, используя популярную заимствованную терминологию, *data-driven*. Хотя данные так или иначе используются почти в любых общественно-географических исследованиях, я исхожу из того, что данная работа целиком и полностью опирается на один базовый массив (набор) данных, подготовка которого представляла собой очень важную (и трудоёмкую) задачу, сопоставимую по сложности и значимости с непосредственным анализом полученных данных. Как было сказано выше, методологически исследование не только проверяет на данных заранее заданные вопросы, но и активно изучает данные для поиска потенциальных тенденций и постановки новых вопросов — иными словами, его ход, задачи и границы во многом определяются характеристиками данных. Возможно, это не самый традиционный подход, но не вижу в нём ничего противозаконного и неэтичного, а значит, в науке он тоже допустим, если приводит к проверяемым, объективным выводам. Сами по себе данные тоже не совсем стандартны: в отличие от многих более типичных исследований, опирающихся преимущественно на официальную статистику, я в качестве основы задействую так называемые административные данные (в основном распространяемые Федеральной налоговой службой — ФНС России), в то время как статистические сведения выступают во вспомогательной роли. Таким образом, вторую цель я кратко обозначил бы так: опробовать методику использования административных данных для data-driven-исследования по общественной географии.


## Структура работы

## Другие небольшие особенности
