# География услуг как часть общественной географии

География — широкая научная область. Она включает в себя множество направлений и специализаций, порой настолько сильно отличающихся друг от друга, что возникают сомнения в оправданности их объединения в одну дисциплину. В кругах географов известен расхожий (хотя и не всегда правильно толкуемый) афоризм Н. Н. Баранского, классика отечественной экономической географии, о широкой сфере интересов географа «от геологии до идеологии». В наиболее общих чертах очевидно, что можно выделить, в частности, географию физическую и географию общественную. Справедливости ради следует заметить, что термин «общественная география» не является однозначно принимаемым, и в ходу альтернативы, такие как «социально-экономическая география» или (следуя полному названию той научной специальности, по которой пишется эта диссертация) «экономическая, социальная, политическая, рекреационная география». Тем не менее, буду здесь и далее использовать именно термин «общественная география», тем более что терминологические вопросы не входят в круг исследования. Также не буду здесь останавливаться на других подразделениях наук о Земле (например, метеорологии и геоинформатике), так как, опять же, это уводит в сторону. Суть этого поверхностного и неполного обзора структуры географических наук в том, чтобы показать: исследование относится к общественной географии, и именно её методология является определяющей.

В рамках общественной географии выделяют такое направление, как география услуг. Её также называют географией сектора услуг, географией социальной инфраструктуры, и наряду с ней часто упоминают географию сферы обслуживания и географию третичного сектора. Весьма подробный и глубокий обзор истории и текущего положения этих научных дисциплин, включающий в себя и некоторые терминологические моменты, можно найти в статье А. А. Ткаченко и А. А. Фомкиной [@Tkachenko2016]. Они отмечают, что география сферы обслуживания появилась в 1960-е годы и быстро завоевала широкое признание: уже на 1970-е годы пришёлся её расцвет. Основная научная и образовательная школа по географии сферы обслуживания сложилась в Московском государственном университете под руководством С. А. Ковалева. В 1990-е годы география сферы обслуживания пришла в упадок, а в 2000-е её нишу стали занимать внешне похожие исследования, также фокусирующиеся на услугах, но тяготяющие к экономической географии, которые стали именоваться географией сектора услуг. В итоге к 2010-м годам в географических исследованиях услуг де-факто сложилось два направления: одно наследует традициям географии сферы обслуживания, а другое представляет собой новую географию сектора услуг. Как следствие, можно выделить два принципиальных подхода к географическому изучению услуг: экономический и социальный.

Зарубежные исследования по географии услуг развивались независимо и обособленно от российских — что, конечно, неудивительно, особенно если учесть, что даже состав и структура географических наук в России и других странах заметно отличаются. Тем не менее, в развитии этого направления заметен некоторый параллелизм с отечественными научными работами, и основные события также происходили в 20 веке. Отдельные вопросы, касающиеся размещения объектов сферы обслуживания, впервые стали рассматриваться в рамках «географии человека» (human geography), которую можно — очень условно — назвать зарубежным аналогом советской экономической географии того времени. В частности, классическое правило У. Рэйли (W. Reilly), известное как «гравитационный закон розничной торговли» (law of retail gravitation), было выведено на основе наблюдений за поведением потребителей, направляющихся из менее крупных городов в более крупные в поисках товаров. Иными словами, речь идёт о географических аспектах торгового обслуживания населения. Исследователь выводит следующие два простых правила: более крупные города притягивают больше покупателей (outside trade), покупатели склонны прибывать из близлежащих городов по сравнению с более удалёнными [@Reilly1931].  Нетрудно увидеть здесь сходства с не менее известной теорией центральных мест, разработанной примерно в то же время в Германии В. Кристаллером (W. Christaller) и изложенной в его работе «Central Places in Southern Germany» (перевод на английский язык вышел в США в 1966 году) [@Christaller1966]. Теория центральных мест, как пишут А. А. Ткаченко и А. А. Фомкина в уже упомянутой статье, имеет прямое отношение к географии сферы обслуживания, являясь одной из двух её теоретических основ наряду с концепцией потребностей А. Маслоу. Тесно связана эта теория и с географией городов, в рамках которой, начиная с середины 20 века, зарубежные специалисты также начинают активно рассматривать вопросы размещения и доступности услуг. В качестве примера можно привести статью Дж. Браша (J. Brush) о географии центральных мест в Юго-Западном Висконсине [@Brush1953], автор которой начинает свои рассуждения с довольно показательного утверждения о том, что крупные центры, *предлагающие больше услуг*, находятся на большем расстоянии друг от друга и менее многочисленны (курсив мой). Похожие работы есть, в частности, и у известного американского географа Дж. Берри (J. Berry) [@Berry1967].